### ISSUE TITLE
Problem to view potree on 3D viewer

### ISSUE THREAD

**Issue by diegorssouza12** [autodesk-platform-services/aps-simple-viewer-nodejs#2]
Hi, im currently using this sample to test the use of potree inside the APS view, but we are just able to view the model inside 2d view only the first access. When we change to the 3D document the cloud is not loaded (and when we go back to the first 2D page the pointcloud disappear ).

Question (1) is : how to set the viewer to show the 3D view only?

Question (2) is : We set the pointcloud, the 3d .dxf and .dwg with the same scale and origin coordinate, but when we load (using scale 1 on threejs) we get the pointcloud larger than .dxf, the position on the lines bellow are (0,0,0) as we have the same coordinates.

\\on main.js
    let position = new THREE.Vector3(0, 0, 0);
    let scale = new THREE.Vector3(1, 1, 1);

![issue](https://user-images.githubusercontent.com/61716160/208116939-193c6c59-d06e-4c10-9115-e8221f7f7c7f.PNG)

Thanks for the attention and sorry for too many questions (Im starting using the APS this month)

Best Regards

**Comment by petrbroz** [comment]
Hi @diegorssouza12,

> how to set the viewer to show the 3D view only?

You control what model is loaded into the viewer, so you can decide whether or not a specific model is loaded based on whether it's 2D or 3D. One option would be to modify [this piece of code](https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/blob/develop/wwwroot/viewer.js#L33-L35) so that instead of loading the _default_ viewable, you load the first viewable that contains 3D geometry data:

```js
function onDocumentLoadSuccess(doc) {
    const views = doc.getRoot().search({ 'role': '3d', 'type': 'geometry' });
    if (views.length > 0) {
        resolve(viewer.loadDocumentNode(doc, views[0]));
    } else {
        reject('Could not find any 3D view.');
    }
}
```

> We set the pointcloud, the 3d .dxf and .dwg with the same scale and origin coordinate, but when we load (using scale 1 on threejs) we get the pointcloud larger than .dxf, the position on the lines bellow are (0,0,0) as we have the same coordinates.

When adding a 3D model into the scene, the viewer may apply various transformations, e.g., a global offset (if the model is too far from the origin, or if it's geo-referenced) or a scale based on the model units. Try and examine the model metadata after it's loaded by the viewer using `viewer.model.getData()`. If you want to align external point cloud data with the model, you'll need to apply the same offset/scale to it.
