### ISSUE TITLE
DocumentBrowser doesnt show the floor plan  nor elevation views

### ISSUE THREAD

**Issue by MiguelG97** [autodesk-platform-services/aps-simple-viewer-nodejs#9]
Hi Folks!

How you are doing great. I have an issue with the document browser extension. Is there any extra setup I need to perform from the Revit side besides this one:
![image](https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/assets/78984964/284338f7-b192-4f9d-88a6-b85c24d52544)
In order to display the selected floorplans and elevations in the document Browser?

The translation job also has set up 2D and 3D views
![image](https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/assets/78984964/1a4bc198-a077-4e3b-95d2-8e1931b1c7c8)

and somehow, my browser only displays the 3D view:

![image](https://github.com/autodesk-platform-services/aps-simple-viewer-nodejs/assets/78984964/ae999b85-c436-4122-b34a-1b05e24dc481)

Any hint on this issue?

All the best,
Miguel G.

**Comment by petrbroz** [comment]
Hi @MiguelG97, this feature should work out-of-the-box. If you try the [live demo](https://aps-simple-viewer-nodejs.autodesk.io/#dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6cGV0cmJyb3otc2FtcGxlcy9ybWVfYWR2YW5jZWRfc2FtcGxlX3Byb2plY3QucnZ0) of this code sample, you can see that the document browser includes various 3D views and 2D sheets.

One thing I've noticed in your screenshots is that you're working with IFC designs rather than Revit designs. Can you clarify what exactly the input data is? Is it a Revit file with an IFC design embedded in it?

**Comment by MiguelG97** [comment]
Got it. Closing this thread since I managed at some point to display the 2d views by grouping them in the project browser
